# Periodically checks the Azure Retail Price API for spot VM availability and prices.
# Inspired by https://simonwillison.net/2020/Oct/9/git-scraping/

name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

permissions:
  id-token: write
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update prices
        shell: pwsh
        run: |
          ./update-data.ps1

      - name: Update CSV
        shell: pwsh
        continue-on-error: true # Workaround for https://github.com/actions/runner/issues/1076
        run: |
          ./data-to-csv.ps1

      - name: Update SkuInfo.bicep
        shell: pwsh
        run: |
          ./build-sku-info.ps1

      - name: Logout
        run: |
          az logout

      - name: Commit and push if data has changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date --iso-8601=seconds)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
